/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankproject;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usman_Ghani_Mughal
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    public FastCash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c500 = new javax.swing.JButton();
        c1000 = new javax.swing.JButton();
        c2000 = new javax.swing.JButton();
        c5000 = new javax.swing.JButton();
        c10000 = new javax.swing.JButton();
        c20000 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c500.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c500.setText("500");
        c500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c500ActionPerformed(evt);
            }
        });
        getContentPane().add(c500, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 84, 89, -1));

        c1000.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c1000.setText("1000");
        c1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1000ActionPerformed(evt);
            }
        });
        getContentPane().add(c1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 84, 80, -1));

        c2000.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c2000.setText("2000");
        c2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2000ActionPerformed(evt);
            }
        });
        getContentPane().add(c2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 142, 89, -1));

        c5000.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c5000.setText("5000");
        c5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5000ActionPerformed(evt);
            }
        });
        getContentPane().add(c5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 142, 80, -1));

        c10000.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c10000.setText("10000");
        c10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10000ActionPerformed(evt);
            }
        });
        getContentPane().add(c10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 200, 89, -1));

        c20000.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c20000.setText("20000");
        c20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c20000ActionPerformed(evt);
            }
        });
        getContentPane().add(c20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 200, -1, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 262, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("       Select Your Amount");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 16, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c500ActionPerformed
        Double amountDouble = 500.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c500ActionPerformed

    private void c1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1000ActionPerformed
      Double amountDouble = 1000.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c1000ActionPerformed

    private void c2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2000ActionPerformed
        Double amountDouble = 2000.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c2000ActionPerformed

    private void c5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5000ActionPerformed
       Double amountDouble = 5000.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c5000ActionPerformed

    private void c10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10000ActionPerformed
       Double amountDouble = 10000.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c10000ActionPerformed

    private void c20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c20000ActionPerformed
       Double amountDouble = 20000.00;
        this.WithDrawl(amountDouble);
    }//GEN-LAST:event_c20000ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      this.setVisible(false);
      new MainMenu(MainMenu.accountId).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
        
    }
    public void WithDrawl(Double ammountDouble)
        {
          try {
             Login_Form.statement = Login_Form.coneConnection.createStatement();
             Login_Form.resultSet = Login_Form.statement.executeQuery("Select Amount from banksystem.account where AccountID ="+MainMenu.accountId);
             if(Login_Form.resultSet.next())
             {
                 Double currentamount = Login_Form.resultSet.getDouble(1);
                 if(currentamount>=ammountDouble)
                 {
                     currentamount = currentamount - ammountDouble;
                     int check = Login_Form.statement.executeUpdate("UPDATE banksystem.account set Amount = "+currentamount+" where AccountID = "+MainMenu.accountId);
                     if(check>0)
                     {
                         JOptionPane.showMessageDialog(this,"You have it : "+ammountDouble);
                     }
                     else
                     {
                        JOptionPane.showMessageDialog(this,"Some things Goes Wrong Try Again");
                     }
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Sorry!! You Do Not have enough blance");
                    
                 }
             }
             else
             {
                 JOptionPane.showMessageDialog(this,"Some things Goes Wrong Try Again");
             }
            
          } catch (SQLException e) {
              System.err.println(e);
          }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton c1000;
    private javax.swing.JButton c10000;
    private javax.swing.JButton c2000;
    private javax.swing.JButton c20000;
    private javax.swing.JButton c500;
    private javax.swing.JButton c5000;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
